### ISSUE TITLE
The footer is invisible

### ISSUE THREAD

**Issue by 6-6-6** [Antoine-lb/upscale-compare#1]
Hello,

Thank you for creating this nice webpage.
I find that the footer is invisible in the current webpage:
 - <img src=https://github.com/user-attachments/assets/3e641dc2-5650-427f-a7d9-bec73b4a3a3a height="250">
 - My browser is: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0

Is this a feature (like an easter egg) ?
If it is not, i can propose a PR to fix it :)
 - <img src=https://github.com/user-attachments/assets/b0f442c4-fa5a-453d-8f9d-16d4744672d8 height="250">
 - from https://github.com/6-6-6/upscale-compare/commit/042793fab9cbb6103a2629f37e800f4e2b94b347

**Comment by Antoine-lb** [comment]
Hello 👋

> Is this a feature (like an easter egg) ?

Sadly, is not an easter egg

> If it is not, i can propose a PR to fix it :)

Please do, I will be happy to accept it

A little off topic, but what do you use it for? I see many AI people coming to it, but I'm wondering if there are more use cases

**Comment by 6-6-6** [comment]
Hello,

> Please do, I will be happy to accept it

Please find it here #2 

> A little off topic, but what do you use it for? I see many AI people coming to it, but I'm wondering if there are more use cases

I use it to compare photos from different cameras, as well as to compare photos before/after editing ;)

**Comment by Antoine-lb** [comment]
Merged 👍 thanks for your contribution.

Just for you to know, this small project is a middle step to introduce image comparison to OneFolder (https://onefolder.app/). Like a small playground to test if everything works well. In case you want to check it out

**Comment by 6-6-6** [comment]
Got it. Thank you for the information!
